menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/tommy351

excerpt_link: Read More

addthis:
  enable: true
  pubid: ra-4daee9911f9dfcb4
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-4910098-7
rss: http://feeds.feedburner.com/zespia